name: Update Blacklist

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行一次
  workflow_dispatch:

jobs:
  update-blacklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull latest changes
      run: git pull origin main --rebase

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests
        pip install ipaddress

    - name: Remove old files
      run: |
        if [ -f transmission_blacklist.txt ]; then rm transmission_blacklist.txt; fi
        if [ -f transmission_blacklist.gz ]; then rm transmission_blacklist.gz; fi

    - name: Run the script
      run: python process_blacklist.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'ci: 👷 Update transmission blacklist'
        git push
